/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author Andrés
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJug1 = new javax.swing.JPanel();
        lblJug1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPrincipal = new javax.swing.JLabel();
        pnlJug2 = new javax.swing.JPanel();
        lblJug2 = new javax.swing.JLabel();
        lblContrincante = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlIconos = new javax.swing.JPanel();
        lblPos6 = new javax.swing.JLabel();
        lblPos7 = new javax.swing.JLabel();
        lblPos8 = new javax.swing.JLabel();
        lblPos16 = new javax.swing.JLabel();
        lblPos15 = new javax.swing.JLabel();
        lblPos14 = new javax.swing.JLabel();
        lblPos22 = new javax.swing.JLabel();
        lblPos23 = new javax.swing.JLabel();
        lblPos24 = new javax.swing.JLabel();
        lblPos21 = new javax.swing.JLabel();
        lblPos13 = new javax.swing.JLabel();
        lblPos5 = new javax.swing.JLabel();
        lblPos11 = new javax.swing.JLabel();
        lblPos3 = new javax.swing.JLabel();
        lblPos19 = new javax.swing.JLabel();
        lblPos18 = new javax.swing.JLabel();
        lblPos10 = new javax.swing.JLabel();
        lblPos2 = new javax.swing.JLabel();
        lblPos17 = new javax.swing.JLabel();
        lblPos9 = new javax.swing.JLabel();
        lblPos1 = new javax.swing.JLabel();
        lblPos20 = new javax.swing.JLabel();
        lblPos12 = new javax.swing.JLabel();
        lblPos4 = new javax.swing.JLabel();
        btnTabla = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pgbTiempo2 = new javax.swing.JProgressBar();
        pgbTiempo1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 100));
        setPreferredSize(new java.awt.Dimension(1190, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlJug1.setBackground(new java.awt.Color(255, 201, 14));
        pnlJug1.setLayout(null);

        lblJug1.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        lblJug1.setForeground(new java.awt.Color(204, 0, 0));
        lblJug1.setText("Jugador 1 ");
        pnlJug1.add(lblJug1);
        lblJug1.setBounds(0, -10, 180, 50);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("00");
        pnlJug1.add(jLabel11);
        jLabel11.setBounds(0, 410, 30, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText(":");
        pnlJug1.add(jLabel9);
        jLabel9.setBounds(30, 410, 20, 40);
        pnlJug1.add(lblPrincipal);
        lblPrincipal.setBounds(20, 380, 80, 30);

        getContentPane().add(pnlJug1);
        pnlJug1.setBounds(10, 10, 150, 440);

        pnlJug2.setBackground(new java.awt.Color(255, 201, 14));
        pnlJug2.setLayout(null);

        lblJug2.setFont(new java.awt.Font("Verdana", 0, 30)); // NOI18N
        lblJug2.setForeground(new java.awt.Color(0, 0, 102));
        lblJug2.setText("Jugador 2");
        pnlJug2.add(lblJug2);
        lblJug2.setBounds(0, -10, 170, 50);
        pnlJug2.add(lblContrincante);
        lblContrincante.setBounds(40, 370, 80, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("00");
        pnlJug2.add(jLabel8);
        jLabel8.setBounds(20, 400, 30, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText(":");
        pnlJug2.add(jLabel13);
        jLabel13.setBounds(50, 400, 10, 40);

        getContentPane().add(pnlJug2);
        pnlJug2.setBounds(1020, 270, 160, 430);

        pnlIconos.setOpaque(false);
        pnlIconos.setLayout(null);
        pnlIconos.add(lblPos6);
        lblPos6.setBounds(0, 350, 60, 35);
        pnlIconos.add(lblPos7);
        lblPos7.setBounds(300, 350, 60, 35);
        pnlIconos.add(lblPos8);
        lblPos8.setBounds(620, 350, 60, 35);
        pnlIconos.add(lblPos16);
        lblPos16.setBounds(540, 290, 60, 35);
        pnlIconos.add(lblPos15);
        lblPos15.setBounds(320, 290, 60, 35);
        pnlIconos.add(lblPos14);
        lblPos14.setBounds(100, 290, 60, 35);
        pnlIconos.add(lblPos22);
        lblPos22.setBounds(210, 240, 60, 35);
        pnlIconos.add(lblPos23);
        lblPos23.setBounds(350, 240, 60, 35);
        pnlIconos.add(lblPos24);
        lblPos24.setBounds(490, 240, 60, 35);
        pnlIconos.add(lblPos21);
        lblPos21.setBounds(500, 170, 60, 35);
        pnlIconos.add(lblPos13);
        lblPos13.setBounds(590, 170, 60, 35);
        pnlIconos.add(lblPos5);
        lblPos5.setBounds(680, 170, 60, 35);
        pnlIconos.add(lblPos11);
        lblPos11.setBounds(620, 60, 60, 35);
        pnlIconos.add(lblPos3);
        lblPos3.setBounds(730, 10, 60, 35);
        pnlIconos.add(lblPos19);
        lblPos19.setBounds(530, 110, 60, 35);
        pnlIconos.add(lblPos18);
        lblPos18.setBounds(400, 110, 60, 35);
        pnlIconos.add(lblPos10);
        lblPos10.setBounds(420, 60, 60, 35);
        pnlIconos.add(lblPos2);
        lblPos2.setBounds(440, 10, 60, 35);
        pnlIconos.add(lblPos17);
        lblPos17.setBounds(260, 110, 60, 35);
        pnlIconos.add(lblPos9);
        lblPos9.setBounds(190, 60, 60, 35);
        pnlIconos.add(lblPos1);
        lblPos1.setBounds(130, 10, 60, 35);
        pnlIconos.add(lblPos20);
        lblPos20.setBounds(230, 170, 60, 35);
        pnlIconos.add(lblPos12);
        lblPos12.setBounds(150, 170, 60, 35);
        pnlIconos.add(lblPos4);
        lblPos4.setBounds(50, 170, 60, 35);

        getContentPane().add(pnlIconos);
        pnlIconos.setBounds(220, 80, 810, 400);

        btnTabla.setText("Tabla");
        getContentPane().add(btnTabla);
        btnTabla.setBounds(400, 10, 90, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagen3.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1100, 0, 110, 920);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Imagen2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -50, 1370, 980);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Fichas Robadas");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 690, 140, 21);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Fichas Robadas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(920, 600, 140, 21);

        pgbTiempo2.setOrientation(1);
        getContentPane().add(pgbTiempo2);
        pgbTiempo2.setBounds(1080, 310, 40, 320);

        pgbTiempo1.setOrientation(1);
        getContentPane().add(pgbTiempo1);
        pgbTiempo1.setBounds(50, 60, 40, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblContrincante;
    private javax.swing.JLabel lblJug1;
    private javax.swing.JLabel lblJug2;
    private javax.swing.JLabel lblPos1;
    private javax.swing.JLabel lblPos10;
    private javax.swing.JLabel lblPos11;
    private javax.swing.JLabel lblPos12;
    private javax.swing.JLabel lblPos13;
    private javax.swing.JLabel lblPos14;
    private javax.swing.JLabel lblPos15;
    private javax.swing.JLabel lblPos16;
    private javax.swing.JLabel lblPos17;
    private javax.swing.JLabel lblPos18;
    private javax.swing.JLabel lblPos19;
    private javax.swing.JLabel lblPos2;
    private javax.swing.JLabel lblPos20;
    private javax.swing.JLabel lblPos21;
    private javax.swing.JLabel lblPos22;
    private javax.swing.JLabel lblPos23;
    private javax.swing.JLabel lblPos24;
    private javax.swing.JLabel lblPos3;
    private javax.swing.JLabel lblPos4;
    private javax.swing.JLabel lblPos5;
    private javax.swing.JLabel lblPos6;
    private javax.swing.JLabel lblPos7;
    private javax.swing.JLabel lblPos8;
    private javax.swing.JLabel lblPos9;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JProgressBar pgbTiempo1;
    private javax.swing.JProgressBar pgbTiempo2;
    private javax.swing.JPanel pnlIconos;
    private javax.swing.JPanel pnlJug1;
    private javax.swing.JPanel pnlJug2;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblPos1() {
        return lblPos1;
    }

    public void setLblPos1(JLabel lblPos1) {
        this.lblPos1 = lblPos1;
    }

    public JLabel getLblPos10() {
        return lblPos10;
    }

    public void setLblPos10(JLabel lblPos10) {
        this.lblPos10 = lblPos10;
    }

    public JLabel getLblPos11() {
        return lblPos11;
    }

    public void setLblPos11(JLabel lblPos11) {
        this.lblPos11 = lblPos11;
    }

    public JLabel getLblPos12() {
        return lblPos12;
    }

    public void setLblPos12(JLabel lblPos12) {
        this.lblPos12 = lblPos12;
    }

    public JLabel getLblPos13() {
        return lblPos13;
    }

    public void setLblPos13(JLabel lblPos13) {
        this.lblPos13 = lblPos13;
    }

    public JLabel getLblPos14() {
        return lblPos14;
    }

    public void setLblPos14(JLabel lblPos14) {
        this.lblPos14 = lblPos14;
    }

    public JLabel getLblPos15() {
        return lblPos15;
    }

    public void setLblPos15(JLabel lblPos15) {
        this.lblPos15 = lblPos15;
    }

    public JLabel getLblPos16() {
        return lblPos16;
    }

    public void setLblPos16(JLabel lblPos16) {
        this.lblPos16 = lblPos16;
    }

    public JLabel getLblPos17() {
        return lblPos17;
    }

    public void setLblPos17(JLabel lblPos17) {
        this.lblPos17 = lblPos17;
    }

    public JLabel getLblPos18() {
        return lblPos18;
    }

    public void setLblPos18(JLabel lblPos18) {
        this.lblPos18 = lblPos18;
    }

    public JLabel getLblPos19() {
        return lblPos19;
    }

    public void setLblPos19(JLabel lblPos19) {
        this.lblPos19 = lblPos19;
    }

    public JLabel getLblPos2() {
        return lblPos2;
    }

    public void setLblPos2(JLabel lblPos2) {
        this.lblPos2 = lblPos2;
    }

    public JLabel getLblPos20() {
        return lblPos20;
    }

    public void setLblPos20(JLabel lblPos20) {
        this.lblPos20 = lblPos20;
    }

    public JLabel getLblPos21() {
        return lblPos21;
    }

    public void setLblPos21(JLabel lblPos21) {
        this.lblPos21 = lblPos21;
    }

    public JLabel getLblPos22() {
        return lblPos22;
    }

    public void setLblPos22(JLabel lblPos22) {
        this.lblPos22 = lblPos22;
    }

    public JLabel getLblPos23() {
        return lblPos23;
    }

    public void setLblPos23(JLabel lblPos23) {
        this.lblPos23 = lblPos23;
    }

    public JLabel getLblPos24() {
        return lblPos24;
    }

    public void setLblPos24(JLabel lblPos24) {
        this.lblPos24 = lblPos24;
    }

    public JLabel getLblPos3() {
        return lblPos3;
    }

    public void setLblPos3(JLabel lblPos3) {
        this.lblPos3 = lblPos3;
    }

    public JLabel getLblPos4() {
        return lblPos4;
    }

    public void setLblPos4(JLabel lblPos4) {
        this.lblPos4 = lblPos4;
    }

    public JLabel getLblPos5() {
        return lblPos5;
    }

    public void setLblPos5(JLabel lblPos5) {
        this.lblPos5 = lblPos5;
    }

    public JLabel getLblPos6() {
        return lblPos6;
    }

    public void setLblPos6(JLabel lblPos6) {
        this.lblPos6 = lblPos6;
    }

    public JLabel getLblPos7() {
        return lblPos7;
    }

    public void setLblPos7(JLabel lblPos7) {
        this.lblPos7 = lblPos7;
    }

    public JLabel getLblPos8() {
        return lblPos8;
    }

    public void setLblPos8(JLabel lblPos8) {
        this.lblPos8 = lblPos8;
    }

    public JLabel getLblPos9() {
        return lblPos9;
    }

    public void setLblPos9(JLabel lblPos9) {
        this.lblPos9 = lblPos9;
    }

    public JLabel getLblContrincante() {
        return lblContrincante;
    }

    public void setLblContrincante(JLabel lblContrincante) {
        this.lblContrincante = lblContrincante;
    }

    public JLabel getLblPrincipal() {
        return lblPrincipal;
    }

    public void setLblPrincipal(JLabel lblPrincipal) {
        this.lblPrincipal = lblPrincipal;
    }

    public JButton getBtnTabla() {
        return btnTabla;
    }

    public void setBtnTabla(JButton btnTabla) {
        this.btnTabla = btnTabla;
    }

    public JProgressBar getPgbTiempo() {
        return pgbTiempo1;
    }

    public void setPgbTiempo(JProgressBar pgbTiempo) {
        this.pgbTiempo1 = pgbTiempo;
    }

    public JProgressBar getPgbTiempo2() {
        return pgbTiempo2;
    }

    public void setPgbTiempo2(JProgressBar pgbTiempo2) {
        this.pgbTiempo2 = pgbTiempo2;
    }

    public JLabel getLblJug1() {
        return lblJug1;
    }

    public void setLblJug1(JLabel lblJug1) {
        this.lblJug1 = lblJug1;
    }

    public JLabel getLblJug2() {
        return lblJug2;
    }

    public void setLblJug2(JLabel lblJug2) {
        this.lblJug2 = lblJug2;
    }

    public JPanel getPnlJug1() {
        return pnlJug1;
    }

    public void setPnlJug1(JPanel pnlJug1) {
        this.pnlJug1 = pnlJug1;
    }

    public JPanel getPnlJug2() {
        return pnlJug2;
    }

    public void setPnlJug2(JPanel pnlJug2) {
        this.pnlJug2 = pnlJug2;
    }

    public JPanel getPnlIconos() {
        return pnlIconos;
    }

    public void setPnlIconos(JPanel pnlIconos) {
        this.pnlIconos = pnlIconos;
    }
    
}
